In [1]:
import torch
from torch.autograd import Variable

In [3]:
x = Variable(torch.randn(3, 4), requires_grad=True)
y = Variable(torch.randn(3, 4), requires_grad=True)
z = Variable(torch.randn(3, 4), requires_grad=True)

In [4]:
x, y, z

(tensor([[-0.7740, -0.3119,  0.6874, -0.9620],
         [-2.9355,  0.5553,  0.0221, -0.1339],
         [ 0.0300, -0.8514, -0.4168, -0.5246]], requires_grad=True),
 tensor([[ 1.4918, -1.3058, -1.5009,  0.2380],
         [-0.9379, -1.9401, -0.4666, -0.9774],
         [ 0.7192,  0.1488,  0.7834, -0.8828]], requires_grad=True),
 tensor([[ 0.1495, -0.6908, -0.7982,  0.8526],
         [ 0.0421, -0.1437,  0.0883,  0.4363],
         [ 0.5104, -0.7456,  0.8341, -0.8168]], requires_grad=True))

In [5]:
a = x * y
a

tensor([[-1.1547,  0.4073, -1.0318, -0.2290],
        [ 2.7531, -1.0773, -0.0103,  0.1308],
        [ 0.0216, -0.1267, -0.3265,  0.4631]], grad_fn=<MulBackward0>)

In [6]:
b = a + z
b

tensor([[-1.0051, -0.2834, -1.8299,  0.6237],
        [ 2.7952, -1.2210,  0.0780,  0.5671],
        [ 0.5320, -0.8723,  0.5076, -0.3537]], grad_fn=<AddBackward0>)

In [8]:
c = torch.sum(b)
c

tensor(-0.4618, grad_fn=<SumBackward0>)

In [9]:
c.backward()

In [13]:
x

tensor([[-0.7740, -0.3119,  0.6874, -0.9620],
        [-2.9355,  0.5553,  0.0221, -0.1339],
        [ 0.0300, -0.8514, -0.4168, -0.5246]], requires_grad=True)

In [12]:
x.grad

tensor([[ 1.4918, -1.3058, -1.5009,  0.2380],
        [-0.9379, -1.9401, -0.4666, -0.9774],
        [ 0.7192,  0.1488,  0.7834, -0.8828]])

In [11]:
x.grad.data

tensor([[ 1.4918, -1.3058, -1.5009,  0.2380],
        [-0.9379, -1.9401, -0.4666, -0.9774],
        [ 0.7192,  0.1488,  0.7834, -0.8828]])

In [14]:
y.grad

tensor([[-0.7740, -0.3119,  0.6874, -0.9620],
        [-2.9355,  0.5553,  0.0221, -0.1339],
        [ 0.0300, -0.8514, -0.4168, -0.5246]])

In [15]:
z.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])